version: 0.1

environment_variables:
  plaintext:
    DATABASE_PORT: 5432
    DATABASE_HOST: dekhoghar.cp6i8ucy2yb8.us-east-1.rds.amazonaws.com
    DATABASE_NAME: dekhoghar
    DATABASE_USER: postgres
    DATABASE_PASSWORD: postgres
    REGION_NAME: None
    AWS_S3_BUCKET: None
    AWS_ACCESS_KEY: None
    AWS_SECRET_KEY: None
    EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
    EMAIL_HOST: smtp.gmail.com
    EMAIL_PORT: 587
    EMAIL_USER: naman.j@example.com
    EMAIL_PASSWORD: qoefnahfckyxtgoj
    EMAIL_FROM: naman.j@example.com
    RESET_URI: http://54.144.70.194/api/user/reset

phases:
  pre_build:
    commands:
      - echo Prebuild ops
      - pip3 install -r requirements.txt
  build:
    commands:
      - echo Building the application 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
